# Generated by Django 5.1.1 on 2024-11-24 06:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_mycosme_mymake'),
    ]

    operations = [
        migrations.CreateModel(
            name='CosmeticMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('brand', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='cosmetics/')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='following',
            field=models.ManyToManyField(related_name='followers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='MyCosmetic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('used_in_make', models.BooleanField(default=False)),
                ('image', models.ImageField(upload_to='cosmetics/')),
                ('is_favorite', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('未使用', '未使用'), ('使用中', '使用中'), ('使用済み', '使用済み')], default='未使用', max_length=10)),
                ('cosmetic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.cosmeticmaster')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cosmetics', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='MyCosme',
        ),
    ]
