# Generated by Django 5.1.1 on 2024-12-01 06:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_cosmeticmaster_user_following_mycosmetic_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cosmeticmaster',
            name='name',
        ),
        migrations.RemoveField(
            model_name='mycosmetic',
            name='image',
        ),
        migrations.RemoveField(
            model_name='mycosmetic',
            name='name',
        ),
        migrations.AddField(
            model_name='cosmeticmaster',
            name='cosmetic_name',
            field=models.CharField(max_length=100, null=True, verbose_name='商品名'),
        ),
        migrations.AddField(
            model_name='cosmeticmaster',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='作成日'),
        ),
        migrations.AddField(
            model_name='cosmeticmaster',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='更新日'),
        ),
        migrations.AddField(
            model_name='mycosmetic',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='作成日'),
        ),
        migrations.AddField(
            model_name='mycosmetic',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='更新日'),
        ),
        migrations.AddField(
            model_name='mymake',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='cosmeticmaster',
            name='brand',
            field=models.CharField(max_length=100, verbose_name='ブランド名'),
        ),
        migrations.AlterField(
            model_name='cosmeticmaster',
            name='category',
            field=models.IntegerField(choices=[(0, 'フェイスケア'), (1, 'ポイントメイク'), (2, 'ベースメイク')], verbose_name='カテゴリ'),
        ),
        migrations.AlterField(
            model_name='cosmeticmaster',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='cosmetics/', verbose_name='画像'),
        ),
        migrations.AlterField(
            model_name='cosmeticmaster',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='価格'),
        ),
        migrations.AlterField(
            model_name='mycosmetic',
            name='cosmetic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.cosmeticmaster', verbose_name='コスメ'),
        ),
        migrations.AlterField(
            model_name='mycosmetic',
            name='is_favorite',
            field=models.BooleanField(default=False, verbose_name='お気に入り'),
        ),
        migrations.AlterField(
            model_name='mycosmetic',
            name='status',
            field=models.CharField(choices=[('未使用', '未使用'), ('使用中', '使用中'), ('使用済み', '使用済み')], default='未使用', max_length=10, verbose_name='使用ステータス'),
        ),
        migrations.AlterField(
            model_name='mycosmetic',
            name='used_in_make',
            field=models.BooleanField(default=False, verbose_name='メイクに使用'),
        ),
        migrations.AlterField(
            model_name='mycosmetic',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cosmetics', to=settings.AUTH_USER_MODEL, verbose_name='ユーザー'),
        ),
        migrations.AlterField(
            model_name='mymake',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
