# Generated by Django 5.1.1 on 2024-12-09 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_mycosmetic_profile_image_mymake_make_memo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mycosmetic',
            name='status',
        ),
        migrations.AddField(
            model_name='cosmeticmaster',
            name='sub_category',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='mycosmetic',
            name='usage_status',
            field=models.CharField(choices=[('not_used', '未使用'), ('in_use', '使用中'), ('used', '使用済み')], default='not_used', max_length=20),
        ),
    ]
