# Generated by Django 5.1.4 on 2024-12-17 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_remove_mycosmetic_status_cosmeticmaster_sub_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mycosmetic',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/'),
        ),
    ]
