# Generated by Django 5.1.4 on 2024-12-17 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_mycosmetic_profile_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mycosmetic',
            name='profile_image',
            field=models.ImageField(blank=True, default='profiles/default.jpg', null=True, upload_to='profiles/'),
        ),
    ]
