# Generated by Django 5.1.4 on 2024-12-20 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_mycosmetic_profile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mycosmetic',
            name='profile_image',
        ),
    ]
