# Generated by Django 5.1.4 on 2024-12-27 14:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_cosmeticmaster_sub_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyMakeCosmetic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_main', models.BooleanField(default=False)),
                ('cosmetic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.cosmeticmaster')),
                ('my_make', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cosmetics', to='app.mymake')),
            ],
        ),
    ]
