# Generated by Django 5.1.4 on 2024-12-30 13:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_follow_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='mymake',
            name='cosmetics',
            field=models.ManyToManyField(related_name='my_makes', through='app.MyMakeCosmetic', to='app.cosmeticmaster'),
        ),
        migrations.AlterField(
            model_name='mymakecosmetic',
            name='cosmetic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cosmetic_my_makes', to='app.cosmeticmaster'),
        ),
        migrations.AlterField(
            model_name='mymakecosmetic',
            name='my_make',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_make_cosmetics', to='app.mymake'),
        ),
    ]
