# Generated by Django 5.1.4 on 2025-01-20 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_alter_cosmeticmaster_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cosmeticmaster',
            name='photo',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='画像のパス'),
        ),
    ]
